### ISSUE TITLE
field data not getting processed correctly !!!

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/bulk-pack-transformer-v2#29]
A lot of the packs are not getting processed.

**Comment by sebastiangaertner** [comment]
It looks like only the first entry gets processed. There are at least 50 users with only 1 capture. https://greenstand.slack.com/archives/CJ0DSKZLH/p1654422094940309

**Comment by sebastiangaertner** [comment]
See https://greenstand.slack.com/archives/CJ0DSKZLH/p1654422094940309
only the first entry gets processed and then it stops. There are at least 50 growers with 1 capture only even though they added many.

**Comment by ZavenArra** [comment]
Fixed.
